name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: cargo run
      # If you add tests, you add uncomment the lines below:
      #- name: Test
      #  run: cargo test 
